package org.sshtunnel.db;

import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class Profile {

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	@DatabaseField
	String name;
	@DatabaseField
	String host;
	@DatabaseField
	String remoteAddress;
	@DatabaseField
	String user;
	@DatabaseField
	String password;
	@DatabaseField
	String keyPath;
	@DatabaseField
	String ssid;
	@DatabaseField
	String proxyedApps;
	
	@DatabaseField
	int port;
	@DatabaseField
	int localPort;
	@DatabaseField
	int remotePort;
	
	@DatabaseField
	boolean isAutoReconnect;
	@DatabaseField
	boolean isAutoConnect;
	@DatabaseField
	boolean isAutoSetProxy;
	@DatabaseField
	boolean isGFWList;
	@DatabaseField
	boolean isSocks;

	Profile() {
		// needed by ormlite
		this("");
	}

	public Profile(String name) {
		this.name = name;
		this.host = "";
		this.port = 22;
		this.localPort = 1984;
		this.remotePort = 3128;
		this.remoteAddress = "127.0.0.1";
		this.user = "";
		this.password = "";
		this.isAutoReconnect = false;
		this.isAutoConnect = false;
		this.isAutoSetProxy = false;
		this.isGFWList = false;
		this.isSocks = false;
		this.keyPath = "/sdcard/sshtunnel/key";
		this.ssid = "";
		this.proxyedApps = "";
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("id=").append(id);
		sb.append(", ").append("name=").append(name);
		return sb.toString();
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getRemoteAddress() {
		return remoteAddress;
	}

	public void setRemoteAddress(String remoteAddress) {
		this.remoteAddress = remoteAddress;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getKeyPath() {
		return keyPath;
	}

	public void setKeyPath(String keyPath) {
		this.keyPath = keyPath;
	}

	public String getSsid() {
		return ssid;
	}

	public void setSsid(String ssid) {
		this.ssid = ssid;
	}

	public String getProxyedApps() {
		return proxyedApps;
	}

	public void setProxyedApps(String proxyedApps) {
		this.proxyedApps = proxyedApps;
	}

	public int getPort() {
		return port;
	}

	public void setPort(int port) {
		this.port = port;
	}

	public int getLocalPort() {
		return localPort;
	}

	public void setLocalPort(int localPort) {
		this.localPort = localPort;
	}

	public int getRemotePort() {
		return remotePort;
	}

	public void setRemotePort(int remotePort) {
		this.remotePort = remotePort;
	}

	public boolean isAutoReconnect() {
		return isAutoReconnect;
	}

	public void setAutoReconnect(boolean isAutoReconnect) {
		this.isAutoReconnect = isAutoReconnect;
	}

	public boolean isAutoConnect() {
		return isAutoConnect;
	}

	public void setAutoConnect(boolean isAutoConnect) {
		this.isAutoConnect = isAutoConnect;
	}

	public boolean isAutoSetProxy() {
		return isAutoSetProxy;
	}

	public void setAutoSetProxy(boolean isAutoSetProxy) {
		this.isAutoSetProxy = isAutoSetProxy;
	}

	public boolean isGFWList() {
		return isGFWList;
	}

	public void setGFWList(boolean isGFWList) {
		this.isGFWList = isGFWList;
	}

	public boolean isSocks() {
		return isSocks;
	}

	public void setSocks(boolean isSocks) {
		this.isSocks = isSocks;
	}
	
	
}
